version: '2'

services:
  vsr-apiserver:
    image: vsr.sakuracr.jp/vsr/vsr-apiserver:staging
    restart: always
    ports:
      - 8913:8913
    volumes:
      - type: bind
        source: ./configs${FIREBASE_CREDENTIALS_FILE_PATH} 
        target: ${FIREBASE_CREDENTIALS_FILE_PATH} 
    environment:
      - DB_USER_NAME=${DB_USER_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOSTNAME=${DB_HOSTNAME}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - VSRECORDER_JWT_SECRET=${VSRECORDER_JWT_SECRET}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_CREDENTIALS_FILE_PATH=${FIREBASE_CREDENTIALS_FILE_PATH}
